{% set name = "digitalearth" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Digital-Earth/archive/{{ version }}.tar.gz
  sha256: 9693835cc266e4607526b85d797ef2c467cda35c737c1bd44d28f08475c74959

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.15
    - pip >=22.3.1
  run:
    - python >=3.9,<3.15
    - numpy >=1.23.3
    - cleopatra >=0.2.3
    - pyramids >=0.2.9
    - gdal >=3.5.3
    - geopandas >=0.12.2
    - geoplot >=0.5.1
    - loguru >=0.6.0


test:
  imports:
    - digitalearth

about:
  home: https://github.com/MAfarrag/Digital-Earth
  license:  GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.md
  summary: Geo-spatial visualization package
  description: |
    Geo-spatial visualization package.
  dev_url: https://github.com/MAfarrag/Digital-Earth
  doc_url: https://digitalearth.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/Digital-Earth/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
