{% set name = "digitalearth" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Digital-Earth/archive/{{ version }}.tar.gz
  sha256: a557c01c02b55fb3d9428e79b6fb3b7b6d3136895817f75fff112bb0a5bccce3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip >=22.3.1
  run:
    - python >=3.9,<3.11
    - pip >=22.3.1
    - numpy >=1.24.1
    - gdal >=3.5.3
    - geopandas >=0.12.2
    - geoplot >=0.5.1
    - cleopatra >=0.2.7
    - pyramids >=0.3.2
    - loguru >=0.6.0


test:
  imports:
    - digitalearth

about:
  home: https://github.com/MAfarrag/Digital-Earth
  license:  GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.md
  summary: Geo-spatial visualization package
  description: |
    Geo-spatial visualization package.
  dev_url: https://github.com/MAfarrag/Digital-Earth
  doc_url: https://digitalearth.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/Digital-Earth/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
