{% set name = "digitalearth" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/Digital-Earth/archive/{{ version }}.tar.gz
  sha256: f48f92563cb960ac7e28c6586c48311ab1fc6c89c4564b33f58657f79af77cda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9.1,<3.10
    - pip >=22.2.2
  run:
    - python >=3.9.1,<3.10
    - numpy >=1.21.2,<1.23.3
    - matplotlib-base >=3.5.3,<3.6.0
    - pyramids >=0.2.2
    - loguru >=0.6.0
    - cleopatra >=0.2.1
    - geoplot >=0.5.1

test:
  imports:
    - digitalearth

about:
  home: https://github.com/MAfarrag/Digital-Earth
  license:  GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.md
  summary: Geo-spatial visualization package
  description: |
    Geo-spatial visualization package.
  dev_url: https://github.com/MAfarrag/Digital-Earth
  doc_url: https://digitalearth.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/Digital-Earth/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
